### ISSUE TITLE
Newest Version does not seem to be setting state topic for sensors

### ISSUE THREAD

**Issue by iceman73** [elad-bar/ha-blueiris#22]
From Debug log
```
2020-01-17 14:10:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': 'garage', 'name': 'Garage Cam', 'room': 'Garage', 'still_image_url': Template("http://192.168.94.99:81/image/garage?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/garage/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': 'front', 'name': 'Front Door Cam', 'room': 'Front Door', 'still_image_url': Template("http://192.168.94.99:81/image/front?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/front/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': 'back', 'name': 'Back Yard', 'room': 'Back Yard', 'still_image_url': Template("http://192.168.94.99:81/image/back?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/back/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': 'Index', 'name': 'All', 'room': None, 'still_image_url': Template("http://192.168.94.99:81/image/Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/Index/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': '@Index', 'name': 'Cycle', 'room': None, 'still_image_url': Template("http://192.168.94.99:81/image/@Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/@Index/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:54 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_api] BlueIrisData initialization with following configuration: base_url: http://192.168.94.99:81, username: 'xxx', 'password': 'xxxx}
2020-01-17 14:10:56 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[garage]: {'id': 'garage', 'name': 'Garage Cam', 'room': 'Garage', 'still_image_url': Template("http://192.168.94.99:81/image/garage?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/garage/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:56 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[front]: {'id': 'front', 'name': 'Front Door Cam', 'room': 'Front Door', 'still_image_url': Template("http://192.168.94.99:81/image/front?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/front/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:56 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[back]: {'id': 'back', 'name': 'Back Yard', 'room': 'Back Yard', 'still_image_url': Template("http://192.168.94.99:81/image/back?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/back/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:56 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[Index]: {'id': 'Index', 'name': 'All', 'room': None, 'still_image_url': Template("http://192.168.94.99:81/image/Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/Index/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:10:56 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[@Index]: {'id': '@Index', 'name': 'Cycle', 'room': None, 'still_image_url': Template("http://192.168.94.99:81/image/@Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/@Index/temp.m3u8', 'username': 'xxx', 'password': 'xxxx}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: garage
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'Garage Cam', 'still_image_url': Template("http://192.168.94.99:81/image/garage?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/garage/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'xxx', 'password': 'xxxx, 'authentication': 'basic'}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity Garage Cam: idle>
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: front
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'Front Door Cam', 'still_image_url': Template("http://192.168.94.99:81/image/front?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/front/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'xxx', 'password': 'xxxx', 'authentication': 'basic'}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity Front Door Cam: idle>
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: back
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'Back Yard', 'still_image_url': Template("http://192.168.94.99:81/image/back?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/back/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'xxx', 'password': 'xxxx', 'authentication': 'basic'}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity Back Yard: idle>
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: Index
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'All', 'still_image_url': Template("http://192.168.94.99:81/image/Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/Index/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'xxx', 'password': 'xxxx', 'authentication': 'basic'}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity All: idle>
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: @Index
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'Cycle', 'still_image_url': Template("http://192.168.94.99:81/image/@Index?q=100&s=100"), 'stream_source': 'http://192.168.94.99:81/h264/@Index/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'xxx', 'password': 'xxxx', 'authentication': 'basic'}
2020-01-17 14:11:04 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity Cycle: idle>
2020-01-17 14:11:08 DEBUG (SyncWorker_2) [custom_components.blueiris.home_assistant] Updating blueiris component at <Event homeassistant_start[L]>
2020-01-17 14:11:08 DEBUG (SyncWorker_2) [custom_components.blueiris.blue_iris_data] update - Start
2020-01-17 14:11:08 DEBUG (SyncWorker_2) [custom_components.blueiris.blue_iris_api] Request to Blue Iris sent to: http://192.168.94.99:81/admin
2020-01-17 14:11:08 DEBUG (SyncWorker_2) [custom_components.blueiris.blue_iris_api] Status of Blue Iris: signal=green
2020-01-17 14:11:08 DEBUG (SyncWorker_2) [custom_components.blueiris.blue_iris_data] update - Completed
```

**Comment by iceman73** [comment]
Config:
## Blue Iris
blueiris:
  host: !secret blueiris_host
  port: !secret blueiris_port
  # [optional] Blue Iris admin username and password
  username: !secret blue_username
  password: !secret blue_password
  # [optional] Blue Iris profile numbers - will create switch if defined
  #   -1 is Default profile
  #   0 is Inactive profile
  #   1-7 profile range
  profile:
    # armed profile number
    armed: 1
    # unarmed profile number
    unarmed: 3
  # List of camera objects
  camera:
      # Camera short name in Blue Iris
    - id: garage
      name: 'Garage Cam'
      room: 'Garage'
    - id: front
      name: 'Front Door Cam'
      room: 'Front Door'
    - id: back
      name: 'Back Yard'
      room: 'Back Yard'
# Binary Sensor
# https://www.home-assistant.io/components/binary_sensor/
binary_sensor:
  # Creates binary sensors according cameras defined in the platform
  - platform: blueiris

# Camera
# https://www.home-assistant.io/components/camera
camera:
  # Creates cameras according to those defined in the platform
  - platform: blueiris

# Switch
# https://www.home-assistant.io/components/switch
switch:
  # Creates switch to arm and disarm BlueIris (available only when profiles and admin password are provided)
  - platform: blueiris

**Comment by remdot** [comment]
I'm having the same issue since the last update. From my logs, it looks like the component is getting events from MQTT just fine, but then the state is not actually changing on the binary sensors (this goes for MOTION, AUDIO and WATCHDOG/Connectivity).

2020-01-22 10:05:29 INFO (MainThread) [custom_components.blueiris.binary_sensor] Handling pnp Motion MOTION_A event with value: ON
2020-01-22 10:05:39 INFO (MainThread) [custom_components.blueiris.binary_sensor] Handling pnp Motion MOTION event with value: OFF

**Comment by elad-bar** [comment]
Please let me know if it solved the issue

**Comment by remdot** [comment]
So far it looks like Motion and Audio sensors are working great, but as far as I can tell so far the Connectivity sensors are not registering anything.

**Comment by Mdleal** [comment]
> So far it looks like Motion and Audio sensors are working great, but as far as I can tell so far the Connectivity sensors are not registering anything.

Same for me

**Comment by elad-bar** [comment]
fixed it as well, on top of it, there was a bug since it opened per camera 3 listeners to MQTT broker (in my case for 16 camera) which casued the HA to stop responding after few minutes.

reworked the entire binary sensor

Added new binary_sensor.blue_iris which indicates whether there's an active alert, attributes are per category (Audio, Motion, Connectivity) presents the list of sensors that are active

**Comment by remdot** [comment]
All three sensors seem to be working perfectly now.

**Comment by iceman73** [comment]
So Motion and Audio are working for me but Connectivity is still not working

**Comment by elad-bar** [comment]
@iceman73, can you install MQTT packet sniffer to check if you are receiving the messages or not?
for me it works great (can you post the json that being sent).

note that at startup the sensor is being set as true and when the message published on / off it will update the sensor.

thanks

**Comment by iceman73** [comment]
I fgured it out for some reason my instance of BlueIris sets &CAM in the watchdog settings to Action when it sends the MQTT. I just hardcoded to short camera name in BlueIris now and its working.

`2020-02-03 10:44:01Topic: BlueIris/Action/StatusQos: 2{ "type": "Connectivity", "trigger": "ON" }`
