### ISSUE TITLE
New Integrations erroring out

### ISSUE THREAD

**Issue by iceman73** [elad-bar/ha-blueiris#25]
When using the latest version, I get the following errors from the system when I try to setup BlueIris from intgrations

2020-02-10 14:46:57 ERROR (MainThread) [homeassistant.setup] Setup failed for blueiris: No setup function defined.

**Comment by tiaanv** [comment]
Same here:
`Setup failed for blueiris: No setup function defined.
5:28 PM setup.py (ERROR)`


`2020-02-11 17:28:22 ERROR (MainThread) [homeassistant.setup] Setup failed for blueiris: No setup function defined.`

**Comment by elad-bar** [comment]
Can you check if you have the blueiris defined somewhere in the YAML?

Thanks

**Comment by tiaanv** [comment]
This was a virgin install, no traces of Blue Iris in any YAML.

**Comment by tiaanv** [comment]
__init__.py completely blank... I'm pretty sure that's not right...
For background.... I got Blue iris installed via HACS.... perhaps the brach/release is corrupt?

**Comment by tiaanv** [comment]
The issue is that the Blue-Iris repo pulled by HACS is incorrect.  I replaced the custom_component files with the github source, and ALL issues were resolved.... bothe the missing text in settings, as reported, as well as this error.... I don't think it is a BI error per se.... more a HACS repo issue?

**Comment by nibotg** [comment]
Thanks, I tried this too and Blue Iris now appears in the list when I 
try to add a new integration. However, when I click on it a small empty 
white box appears and then disappears immediately.

Thanks

**Comment by tiaanv** [comment]
What I did:

- Delete the contents of the blueiris folder
- Copy all files from the github "blueiris" folder under custom_controls.
- Restarted HA

Mine worked...

**Comment by nibotg** [comment]
Thanks again, tried that again and unfortunately I still don't get to 
the box to enter the details. Opens but closes immediately.

Thanks

**Comment by iceman73** [comment]
This is now solved and working as expected

**Comment by nibotg** [comment]
Hi, sorry but I still have the problem, I shared the requested log file earlier today. Can you advise what I need to do please?

Thanks
